#%RAML 1.0 NamedExample

- homeTeam: BAR
  awayTeam: RMA
  date: "2017-01-12T20:00:00"
  homeTeamScore: 12
  awayTeamScore: 10

- homeTeam: RMA
  awayTeam: ATL
  date: "2017-01-13T20:00:00"
  homeTeamScore: 5
  awayTeamScore: 25