#%RAML 1.0 NamedExample

- id: "2"
  homeTeam: BAR
  awayTeam: RMA
  date: "2017-07-12T20:00:00"
  homeTeamScore: 3
  awayTeamScore: 0
- id: "3"
  homeTeam: ATL
  awayTeam: RMA
  date: "2017-07-13T20:00:00"
  homeTeamScore: 4
  awayTeamScore: 5