#%RAML 1.0 NamedExample

- position: 1
  team: TRI
  points: 36
  matchesPlayed: 12
  matchesWon: 10
  matchesDraw: 0
  matchesLost: 2
  goalsInFavor: 15
  goalsAgainst: 6

- position: 2
  team: CII
  points: 36
  matchesPlayed: 12
  matchesWon: 10
  matchesDraw: 0
  matchesLost: 2
  goalsInFavor: 15
  goalsAgainst: 6