#%RAML 1.0 DataType
description: An standing position of a team whitin a tournament
type: position
properties:
  id:
example:
 id: "1"
 position: 1
 team: "ZZZ"
 points: 36
 matchesPlayed: 12
 matchesWon: 10
 matchesDraw: 0
 matchesLost: 2
 goalsInFavor: 15
 goalsAgainst: 6